### ISSUE TITLE
website: Update Hugo to latest version

### ISSUE THREAD

**Issue by akronb** [ooni/ooni.org#1216]
I can't run local build because the site is incompatible with the latest version of `hugo` that I installed via `brew` (unfortunately, brew has disabled the ability to install older versions of applications).

I ended up installing `hugo v0.76.5` from tarball. It is possible, but requires extra time to look into the issue. That is why I propose to try to update the site to the latest version of `hugo` or write instructions on how to install it correctly.

Also, README states that the "canonical" version of `hugo` is specified in `travis.yml`, but this file is not in the repository.

**Comment by hellais** [comment]
Yes I agree we should update the site to the latest version of hugo. The last time I tried using the latest version I seem to recall that there were some issues with it, but I don't remember the details.

We have since switched to github actions and netlify, but haven't updated the Readme to reflect that. The versions we pin hugo to are defined in here:
* https://github.com/ooni/ooni.org/blob/master/netlify.toml#L6
* https://github.com/ooni/ooni.org/blob/master/.github/workflows/main.yml#L21

**Comment by hellais** [comment]
We have now upgraded to 0.111.3: https://github.com/ooni/ooni.org/commit/0cab823a804e6305cba3c020799544700942ecaf
