### ISSUE TITLE
untitled "Thematic OONI Probe testing" page

### ISSUE THREAD

**Issue by xhdix** [ooni/ooni.org#296]
https://ooni.org/get-involved/run/
`<title>OONI - </title>`
The value of `{{.Title}}` is not received.
https://github.com/TheTorProject/ooni-web/blob/f12b92321478e90e6e22c8039567f298db8fcb95/layouts/partials/head.html#L10

**Comment by hellais** [comment]
Thanks for reporting this. I will look into fixing this in the next cycle.

**Comment by hellais** [comment]
I tried debugging this and it appears that we are following a very old hugo version pattern for implementing the layouts.
We should instead of using partials, rather be using the `baseof.html` layout, see: https://gohugo.io/templates/base/,

Implementing this change will break done for revamping the website in: https://github.com/ooni/ooni.org/pull/305, so I suggest we land that and then move to doing this refactor.
