### ISSUE TITLE
Improve data visualizations included in OTF Fellow report

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#441]
We have received the following feedback for the improvement of the charts (generated based on OONI data) included in the report of the OTF Fellow we're hosting.

"The quality of image on pages 23, 32 and 35 looked poor.  Maybe increase size and break up over two pages? 

Can the legend be shorter in some cases? It is a lot info to digest but maybe its better to just keep it standard. "

I would also propose the following improvements to the charts:

1. Remove all the "unnecessary" legends that aren't displayed in the charts (e.g. tcp, dns, etc.) and only include "confirmed blocked", "http-diff" (for the cases where block pages are detected through manual analysis), and "accessible". 

2. Add the OONI logo to the charts.

**Comment by hellais** [comment]
I have tightened up a bit the charts so that they occupy less vertical space.

I have also updated the media and filesharing ones such that the miscategorised sites are fixed.

For the time being, since it requires quite some work and is dependant on the desired output data format, I am not going to add the logo to them just yet.

That will be done in coordination with the learning lab once they communicate to me in which format they would like the charts and if some additional layout is needed for them.

**Comment by hellais** [comment]
The charts have been updated in the source document.

I can provide if needed vector versions of the chart for use by the designers of the final layout. If there are people doing layout it's probably best for them to add the OONI logo directly as part of the layout and design process.
