### ISSUE TITLE
OONI Probe Desktop 3.0.4

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#600]

**Comment by bassosimone** [comment]
Moving to next sprint and transferring the points to https://github.com/ooni/probe-engine/issues/893.

**Comment by bassosimone** [comment]
We are not going to finalise this task in this Sprint. Let us move this issue into the next Sprint.

**Comment by bassosimone** [comment]
This release is going to contain probe-cli v3.0.8, which fixes https://github.com/ooni/explorer/issues/495, along with some improvements in the user interface. Because addressing https://github.com/ooni/explorer/issues/495 is quite important, we are prioritising releasing a new version over including more user interface improvements.

**Comment by bassosimone** [comment]
We're making progress in making the release. We're currently testing v3.0.4-rc.1. We are specifically focusing on whether the binaries are WAI on Windows and macOS, on improving the automatic publishing and signing process. Because we'll be spending part of today (Thursday) testing and we don't release on Friday, I guess the release will happen early next week.

**Comment by bassosimone** [comment]
I was able to publish https://github.com/ooni/probe-desktop/releases/tag/v3.0.4-rc.3 from command line using the following command line that has been provided to me by @sarathms (thanks!):

```bash
yarn publish:mac -c.mac.publish.provider=github -c.mac.publish.releaseType=prerelease
```

Now, it seems to me that publishing a prerelease by default is the right thing to do even for releases. We can then manually go into the release and force the transition from prerelease to release. In my view, this reduces the risk that we commit some operational mistake and bless a release before it is time when manually creating a release.

I think this could be a good topic for discussion with @sarathms later toray.

**Comment by bassosimone** [comment]
This issue is morally done! The binary release has been pushed yesterday night. I am going to add @agrabeli to the assignees because we need to sync up with here regarding announcing the availability of this release. So, this issue could be a good synchronisation point that may help us to remember about this final step w/o creating issue overloading.

**Comment by bassosimone** [comment]
With the merging of https://github.com/ooni/ooni.org/pull/637, I think we're now done. Let us close this issue!
