### ISSUE TITLE
Measure HTTPS middleboxes

### ISSUE THREAD

**Issue by thewebdev** [ooni/ooni.org#621]
Tested -

Version: OONI Probe 3.0.3  
Platform: macOS Mojave 10.14.6
ISP: Bharti Airtel Limited [AS24560 (IN)]

OONI Probe isn't able to identify any middleboxes through the *HTTP Invalid Request Line Test* and *Http Header Field Manipulation Test* on the ISP cited above. This report however states and shows that [Airtel does use Middleboxes for censoring HTTPS traffic](http://iamkush.me/sni-airtel/).

**Comment by bassosimone** [comment]
The two experiments you mention do not measure the presence of HTTPS middleboxes. I believe the right thing to do here is to see whether we can implement the methodology developed by kush and run it alongside other middlebox tests.

**Comment by thewebdev** [comment]
> The two experiments you mention do not measure the presence of HTTPS middleboxes. 

Then the UI and / or reults needs to be reworked / reworded because the results of test suggests that it is used for just that. Please see attached screenshots:

![no-middle-box](https://user-images.githubusercontent.com/1777578/97106416-6093ec80-16b9-11eb-81eb-3210feefacda.jpg)

![http-invalid-line](https://user-images.githubusercontent.com/1777578/97106417-67226400-16b9-11eb-9196-9f8cb06e4682.png)

![http-headr-field](https://user-images.githubusercontent.com/1777578/97106420-6b4e8180-16b9-11eb-9abd-108ce8d7d3b0.png)

**Comment by bassosimone** [comment]
> Then the UI and / or results of the test needs to be reworked / reworded because the results of test suggests that it is used for just that [...]

I see your point. I thought that the fact that both experiments are called "HTTP <something>" was enough to signal that they were searching for HTTP middleboxes rather than for TLS middleboxes for censoring HTTPS.

I also have an additional question: what version of the app are you using? I'm running 2.7.0 and the middleboxes tests group has now been removed (this refactoring happened in May 2020 with [2.4.0](https://github.com/ooni/probe-android/releases/tag/v2.4.0)). They have been grouped with performance. Would you mind checking whether your concerns about the UX still hold with version 2.7.0?

Thank you!

**Comment by bassosimone** [comment]
We're going to start working on TLS middleboxes in https://github.com/ooni/probe-engine/issues/1054. We can close this issue because we have a more specific way forward and because the standalone middlebox field is gone, hence also the source of legitimate UX confusion regarding them is gone. Adding the duplicate flag to signal we're closing because we have a more specific sort of duplicate issue.
