### ISSUE TITLE
Write copy for new Donate page

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#713]
We are busy developing a new Donate page for the OONI website. I'll be writing the copy for that page.

**Comment by Vivsss** [comment]
![UI - OONI Donate Page](https://user-images.githubusercontent.com/15786265/101630601-67857d00-3a23-11eb-97eb-3b0ef45b4413.jpg)

**Comment by Vivsss** [comment]
HI Maria, here a first graphic, within  the OONI illustration on the left of the page. Can you work on copy by this sketch? So I could finilise spaces, the lenght of the page and the illustration?

**Comment by agrabeli** [comment]
Thank you @Vivsss, the mockup is great! I'll try to get to the copy by the end of this week.

Is there flexibility to disable (temporarily) the gift part of the page? I'm asking as we don't currently have capacity to ship t-shirts (and other swag), but we'd like to be able to do so in the future.

**Comment by Vivsss** [comment]
Thanks @agrabeli !
Yes, we'll do this section flexible according to the needs

**Comment by hellais** [comment]
A few comments on the above graphics:
* The OONI logo in the upper right should be the monochrome inverted one (white)
* I am not too convinced of using the primary color (OONI Blue) for the background of the text "DONATE NOW TO SUPPORT INTERNET FREEDOM", because it doesn't flow so nicely with the header, maybe we can use the secondary color here?
* Perhaps (related to the above), we can instead put a banner with the ocean graphics and then put all the text below. This would also flow better on mobile.

**Comment by Vivsss** [comment]
1. The OONI logo in the upper right should be the monochrome inverted one (white) : SURE :D
2. I am not too convinced of using the primary color (OONI Blue) for the background of the text "DONATE NOW TO SUPPORT INTERNET FREEDOM", because it doesn't flow so nicely with the header, maybe we can use the secondary color here? : Yes, we can test it while we develop the page
3. Perhaps (related to the above), we can instead put a banner with the ocean graphics and then put all the text below. This would also flow better on mobile. : in the mobile version, I think  to exclude the ocean graphics or put it in the background, to make the page neither too long nor too charged

We'll speak of all that tomorrow in our call? :)

**Comment by Vivsss** [comment]
Thanks @agrabeli <3

**Comment by agrabeli** [comment]
@Vivsss I *might* make some final, minor edits before we publish the page (in which case, I'll do the edits directly in the pull request).

Please note that I have *not* included the final paragraph in the mockup with the privacy policy, since we only have a data policy which is irrelevant (since it's about OONI measurements). :p 

The copy in the banner ("Donate now to support internet freedom") is good as is. :)

**Comment by Vivsss** [comment]
![UI - OONI Donate Page + Copy](https://user-images.githubusercontent.com/15786265/102110952-17008c00-3e36-11eb-9ee3-7e7ee1b9be04.jpg)

**Comment by Vivsss** [comment]
This is a wireframe for the mobile version of the Donate page

<img width="185" alt="Wireframe - OONI Donate Page - Mobile" src="https://user-images.githubusercontent.com/15786265/102112655-4a441a80-3e38-11eb-87d0-aab72edcd39e.png">

**Comment by hellais** [comment]
This is done.
